#  spring:
#    h2:
#      console:
#        enabled: true
#        path: /h2-console
#    datasource:
#      url: jdbc:h2:mem:ISdb
#      username: sa
#      password:
#      initialization-mode: always
  spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Information_System
    username:mysql
    password:mysql
#    jpa:
#      hibernate.ddl-auto: update
#      generate-ddl: true
#      show-sql: true